name: flutter_qualtrics
description: Qualitrics mobile SDK wrapper
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any

flutter:
  plugin:
    androidPackage: be.vrt.flutter_qualtrics
    pluginClass: QualtricsFlutterPlugin
